/*
- Dissolve roofprints and enrich attribute data with parcels
- Convert flood zone and floodway categories into quantitative risk levels,
where HHZ is the highest risk level (4) and the 500-year is the lowest (1)
*/

-- DROP TABLES

DROP TABLE IF EXISTS PROC.TOUCHING_ROOFPRINTS CASCADE;

DROP TABLE IF EXISTS PROC.DISSOLVED_ROOFPRINTS CASCADE;

DROP TABLE IF EXISTS CLEAN.ROOFPRINTS CASCADE;

DROP TABLE IF EXISTS CLEAN.FLOODPLAINS CASCADE;


-- CREATE TABLES

CREATE TABLE PROC.TOUCHING_ROOFPRINTS (
    BLDGTYPE TEXT,
    BLDGYEAR INTEGER,
    MULTIROOF INTEGER,
    GEOM GEOMETRY(POLYGON, 2876) NOT NULL
);

CREATE TABLE PROC.DISSOLVED_ROOFPRINTS (
    BLDGTYPE TEXT,
    BLDGYEAR INTEGER,
    MULTIROOF INTEGER,
    CENTROID GEOMETRY(POINT, 2876) NOT NULL,
    GEOM GEOMETRY(POLYGON, 2876) NOT NULL
);

CREATE TABLE CLEAN.ROOFPRINTS (
    OID SERIAL PRIMARY KEY,
    STRADDRESS TEXT,
    BLDGTYPE TEXT,
    BLDGYEAR INTEGER,
    MULTIROOF INTEGER,
    GEOM GEOMETRY(POLYGON, 2876) NOT NULL
);

CREATE TABLE CLEAN.FLOODPLAINS (
	OID SERIAL PRIMARY KEY,
	RISKLEVEL INTEGER,
	EFFRANGE DATERANGE,
	GEOM GEOMETRY(POLYGON, 2876) NOT NULL
);


-- CREATE SPATIAL INDEXES

CREATE INDEX TOUCHING_ROOFPRINTS_GEOM_IDX ON PROC.TOUCHING_ROOFPRINTS USING GIST(GEOM);

CREATE INDEX DISSOLVED_ROOFPRINTS_GEOM_IDX ON PROC.DISSOLVED_ROOFPRINTS USING GIST(GEOM);
CREATE INDEX DISSOLVED_ROOFPRINTS_CENTROID_IDX ON PROC.DISSOLVED_ROOFPRINTS USING GIST(CENTROID);

CREATE INDEX ROOFPRINTS_GEOM_IDX ON CLEAN.ROOFPRINTS USING GIST(GEOM);

CREATE INDEX FLOODPLAINS_GEOM_IDX ON CLEAN.FLOODPLAINS USING GIST(GEOM);


-- INSERT DATA THRU SOME WIZARDRY

-- TOUCHING ROOFPRINTS
INSERT INTO PROC.TOUCHING_ROOFPRINTS
SELECT R1.BLDGTYPE,
    R1.BLDGYEAR,
    1,
    (ST_DUMP(ST_UNION(R1.GEOM))).GEOM
FROM PROC.ROOFPRINTS R1,
    PROC.ROOFPRINTS R2
WHERE ST_INTERSECTS(R1.GEOM, R2.GEOM)
    AND R1.OID <> R2.OID
GROUP BY R1.BLDGTYPE,
    R1.BLDGYEAR;

-- DISSOLVED AND MERGED ROOFPRINTS
INSERT INTO PROC.DISSOLVED_ROOFPRINTS
SELECT SINGLE.BLDGTYPE,
	SINGLE.BLDGYEAR,
    0,
    ST_POINTONSURFACE(SINGLE.GEOM) CENTROID,
	SINGLE.GEOM
FROM PROC.ROOFPRINTS SINGLE
LEFT JOIN PROC.TOUCHING_ROOFPRINTS TOUCH ON ST_INTERSECTS(SINGLE.GEOM, TOUCH.GEOM)
WHERE TOUCH.GEOM IS NULL
UNION ALL
SELECT BLDGTYPE,
    BLDGYEAR,
    MULTIROOF,
    ST_POINTONSURFACE(GEOM),
    GEOM
FROM PROC.TOUCHING_ROOFPRINTS;

-- ENRICHED ROOFPRINTS
INSERT INTO CLEAN.ROOFPRINTS (STRADDRESS, BLDGTYPE, BLDGYEAR, MULTIROOF, GEOM)
SELECT PAR.STRADDRESS,
	ROOF.BLDGTYPE,
	COALESCE(ROOF.BLDGYEAR, PAR.BLDGYEAR), -- prefer the build year on the building, otherwise grab it from the parcel
	ROOF.MULTIROOF,
	ROOF.GEOM
FROM PROC.DISSOLVED_ROOFPRINTS ROOF
LEFT JOIN PROC.PARCELS PAR ON ST_INTERSECTS(ROOF.CENTROID, PAR.GEOM);

-- ENRICHED FLOODPLAINS
INSERT INTO CLEAN.FLOODPLAINS (RISKLEVEL, EFFRANGE, GEOM)
SELECT 
	CASE
		WHEN FLOODZONE = 'HHZ' THEN 4 -- high hazard zone is most dangerous/likely
		WHEN FLOODZONE like 'A%' AND FLOODWAY = 1 THEN 3 -- conveyance zone is next
		WHEN FLOODZONE like 'A%' AND FLOODWAY <> 1 THEN 2 --100 year
		WHEN FLOODZONE in ('X', 'B') THEN 1 -- 500 year
	END RISKLEVEL,
	EFFRANGE,
	GEOM
FROM PROC.FLOODPLAINS;