/*
Union flood polygons so there are no overlapping geometeries within RISKIESTs,
and each resultant polygon has the flood history for each RISKIEST category in
that area.
 */
 
 -- DROP TABLES

DROP TABLE IF EXISTS CLEAN.FLOODPLAINS CASCADE;


-- CREATE TABLES

CREATE TABLE CLEAN.FLOODPLAINS (
	OID serial PRIMARY KEY,
	RISKIEST integer,
	FROMDATE date,
	TODATE date,
	GEOM GEOMETRY(POLYGON, 2876) NOT NULL
);


-- CREATE SPATIAL INDEXES

CREATE INDEX FLOODPLAINS_GEOM_IDX ON CLEAN.FLOODPLAINS USING GIST(GEOM);


-- INSERT DATA

INSERT INTO CLEAN.FLOODPLAINS (RISKIEST, FROMDATE, TODATE, GEOM)
SELECT 
	CASE
		WHEN FLOODZONE = 'HHZ' THEN 4 -- high hazard zone is most dangerous/likely
		WHEN FLOODZONE like 'A%' AND FLOODWAY = 1 THEN 3 -- conveyance zone is next
		WHEN FLOODZONE like 'A%' AND FLOODWAY <> 1 THEN 2 --100 year
		WHEN FLOODZONE in ('X', 'B') THEN 1 -- 500 year
	END RISKIEST,
	FROMDATE,
	TODATE,
	GEOM
FROM PROC.FLOODPLAINS;