/* Dissolve roofprints and enrich attribute data with parcels */

-- DROP TABLES

DROP TABLE IF EXISTS PROC.TOUCHING_ROOFPRINTS CASCADE;
DROP TABLE IF EXISTS PROC.DISSOLVED_ROOFPRINTS CASCADE;
DROP TABLE IF EXISTS PROC.ENRICHED_ROOFPRINTS CASCADE;

-- CREATE TABLES

CREATE TABLE PROC.TOUCHING_ROOFPRINTS (
    BLDGTYPE VARCHAR,
    BLDGYEAR INTEGER,
    MULTIROOF INTEGER,
    GEOM GEOMETRY(POLYGON, 2876) NOT NULL
);

CREATE TABLE PROC.DISSOLVED_ROOFPRINTS (
    BLDGTYPE VARCHAR,
    BLDGYEAR INTEGER,
    MULTIROOF INTEGER,
    GEOM GEOMETRY(POLYGON, 2876) NOT NULL
);

CREATE TABLE CLEAN.ROOFPRINTS (
    OID SERIAL PRIMARY KEY,
    STRADDRESS VARCHAR,
    BLDGTYPE VARCHAR,
    BLDGYEAR INTEGER,
    MULTIROOF INTEGER,
    CENTROID GEOMETRY(POINT, 2876) NOT NULL,
    GEOM GEOMETRY(POLYGON, 2876) NOT NULL
);

-- CREATE SPATIAL INDEXES

CREATE INDEX TOUCHING_ROOFPRINTS_GEOM_IDX ON PROC.TOUCHING_ROOFPRINTS USING GIST(GEOM);

CREATE INDEX DISSOLVED_ROOFPRINTS_GEOM_IDX ON PROC.DISSOLVED_ROOFPRINTS USING GIST(GEOM);

CREATE INDEX ROOFPRINTS_GEOM_IDX ON CLEAN.ROOFPRINTS USING GIST(GEOM);
CREATE INDEX ROOFPRINTS_CENTROID_IDX ON CLEAN.ROOFPRINTS USING GIST(CENTROID);


-- INSERT DATA THRU SOME WIZARDRY

INSERT INTO PROC.TOUCHING_ROOFPRINTS
SELECT R1.BLDGTYPE,
    R1.BLDGYEAR,
    1,
    (ST_DUMP(ST_UNION(R1.GEOM))).GEOM
FROM PROC.ROOFPRINTS R1,
    PROC.ROOFPRINTS R2
WHERE ST_INTERSECTS(R1.GEOM, R2.GEOM)
    AND R1.OID <> R2.OID
GROUP BY R1.BLDGTYPE,
    R1.BLDGYEAR;

INSERT INTO PROC.DISSOLVED_ROOFPRINTS
SELECT SINGLE.BLDGTYPE,
	SINGLE.BLDGYEAR,
    0,
	SINGLE.GEOM
FROM PROC.ROOFPRINTS SINGLE
LEFT JOIN PROC.TOUCHING_ROOFPRINTS TOUCH ON ST_INTERSECTS(SINGLE.GEOM, TOUCH.GEOM)
WHERE TOUCH.GEOM IS NULL
UNION ALL
SELECT *
FROM PROC.TOUCHING_ROOFPRINTS;

INSERT INTO CLEAN.ROOFPRINTS (STRADDRESS, BLDGTYPE, BLDGYEAR, MULTIROOF, CENTROID, GEOM)
WITH CENTROIDS AS
	(SELECT *,
	 	ST_POINTONSURFACE(GEOM) CENTROID
	 FROM PROC.DISSOLVED_ROOFPRINTS)
SELECT PAR.STRADDRESS,
	CEN.BLDGTYPE,
	COALESCE(CEN.BLDGYEAR, PAR.BLDGYEAR), -- prefer the build year on the building, otherwise grab it from the parcel
	CEN.MULTIROOF,
    CEN.CENTROID,
	CEN.GEOM
FROM CENTROIDS CEN
LEFT JOIN PROC.PARCELS PAR ON ST_INTERSECTS(CEN.CENTROID, PAR.GEOM);