/*
Extract all contiguous ranges when a structure was in a given risk level
for flooding.
*/

DROP TABLE IF EXISTS CLEAN.RISKHISTORY;

CREATE TABLE CLEAN.RISKHISTORY (
	ROOFID INTEGER,
	RISKLEVEL INTEGER,
	RISKDATES DATERANGE,
	FOREIGN KEY (ROOFID) REFERENCES CLEAN.ROOFPRINTS (OID)
);

INSERT INTO CLEAN.RISKHISTORY
-- with help from https://dba.stackexchange.com/a/102239/241989
SELECT OID,
	RISKIEST,
	DATERANGE(
		FROMDATE,
		COALESCE(LEAD(MAXPREVTODATE) OVER (PARTITION BY OID, RISKIEST 
										   ORDER BY FROMDATE),
				 MAXTODATE))
FROM (
	SELECT
		R.OID,
		F.RISKIEST,
		F.FROMDATE,
		F.TODATE,
		MAX(COALESCE(F.TODATE, 'infinity'::DATE))
			OVER (PARTITION BY R.OID, F.RISKIEST
				  ORDER BY F.FROMDATE
				  ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) MAXPREVTODATE,
		MAX(COALESCE(F.TODATE, 'infinity'::DATE))
			OVER (PARTITION BY R.OID, F.RISKIEST) MAXTODATE
	FROM CLEAN.ROOFPRINTS R
	INNER JOIN CLEAN.FLOODPLAINS F ON ST_INTERSECTS(R.GEOM, F.GEOM)
) HIST
WHERE (MAXPREVTODATE IS NULL OR FROMDATE > MAXPREVTODATE);
