/*
Extract all contiguous ranges when a structure was in a given risk level
for flooding.
*/

DROP TABLE IF EXISTS CLEAN.RISKHISTORY;

CREATE TABLE CLEAN.RISKHISTORY (
	ROOFID INTEGER,
	RISKLEVEL INTEGER,
	FROMDATE DATE,
	TODATE DATE,
	FOREIGN KEY (ROOFID) REFERENCES CLEAN.ROOFPRINTS (OID)
);

INSERT INTO CLEAN.RISKHISTORY
-- with help from https://dba.stackexchange.com/a/102239/241989
SELECT OID,
	RISKLEVEL,
	FROMDATE,
	COALESCE(LEAD(MAXPREVTODATE) OVER (PARTITION BY OID, RISKLEVEL 
										   ORDER BY FROMDATE),
				 MAXTODATE)) TODATE
FROM (
	SELECT
		R.OID,
		F.RISKLEVEL,
		LOWER(F.EFFRANGE) FROMDATE,
		MAX(UPPER(F.EFFRANGE))
			OVER (PARTITION BY R.OID, F.RISKLEVEL
				  ORDER BY LOWER(F.EFFRANGE)
				  ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) MAXPREVTODATE,
		MAX(UPPER(F.EFFRANGE))
			OVER (PARTITION BY R.OID, F.RISKLEVEL) MAXTODATE
	FROM CLEAN.ROOFPRINTS R
	INNER JOIN CLEAN.FLOODPLAINS F ON ST_INTERSECTS(R.GEOM, F.GEOM)
) HIST
WHERE (MAXPREVTODATE IS NULL OR FROMDATE > MAXPREVTODATE);
