DROP TABLE IF EXISTS FLOOD.FLOODPLAINS CASCADE;

-- create the table from a selection on the sandbox

CREATE TABLE FLOOD.FLOODPLAINS AS
SELECT OBJECTID,
	FLOODZONE,
	FLOODWAY,
	DRAINAGE,
	EFFDATE::date,
	INEFFDATE::date,
	WKB_GEOMETRY GEOM
FROM SANDBOX.FLOODPLAINS;

-- create spatial index

CREATE INDEX IF NOT EXISTS FLOODPLAINS_GEOM_IDX ON FLOOD.FLOODPLAINS USING GIST(GEOM);

-- create sequence and make it the primary key

CREATE SEQUENCE IF NOT EXISTS FLOOD.FLOODPLAINS_ID_SEQ OWNED BY FLOOD.FLOODPLAINS.OBJECTID;


ALTER TABLE FLOOD.FLOODPLAINS
ALTER COLUMN OBJECTID
SET DEFAULT NEXTVAL('FLOOD.FLOODPLAINS_ID_SEQ'::REGCLASS);


ALTER TABLE FLOOD.FLOODPLAINS ADD CONSTRAINT FLOODPLAINS_PK PRIMARY KEY (OBJECTID);

-- alter geometry column to not accept null values

ALTER TABLE FLOOD.FLOODPLAINS
ALTER COLUMN GEOM
SET NOT NULL;