DROP TABLE IF EXISTS PROC.TOUCHING_ROOFPRINTS CASCADE;


CREATE TABLE PROC.TOUCHING_ROOFPRINTS AS
-- with help from https://gis.stackexchange.com/a/187814/114009
SELECT 1 MULTIROOF,
	R1.BLDGTYPE,
	R1.BLDGYEAR,
	ST_UNION(R1.GEOM) GEOM
FROM PROC.ROOFPRINTS R1,
	PROC.ROOFPRINTS R2
WHERE ST_INTERSECTS(R1.GEOM, R2.GEOM)
	AND R1.OID <> R2.OID
GROUP BY R1.BLDGTYPE,
	R1.BLDGYEAR;


CREATE INDEX IF NOT EXISTS TOUCHING_ROOFPRINTS_GEOM_IDX ON PROC.TOUCHING_ROOFPRINTS USING GIST(GEOM);