DROP TABLE IF EXISTS PROC.ROOFPRINTS CASCADE;

-- create the table used to porcess data

CREATE TABLE PROC.ROOFPRINTS (
	OID SERIAL PRIMARY KEY,
	BLDGTYPE VARCHAR,
	BLDGYEAR INTEGER,
	CENTROID GEOMETRY(POINT, 2876) NOT NULL,
	GEOM GEOMETRY(POLYGON, 2876) NOT NULL
);

-- insert values from raw data

INSERT INTO PROC.ROOFPRINTS (BLDGTYPE, BLDGYEAR, CENTROID, GEOM)
SELECT BLDGTYPE,
	BUILDYEAR,
	ST_POINTONSURFACE((ST_DUMP(WKB_GEOMETRY)).GEOM),
	(ST_DUMP(WKB_GEOMETRY)).GEOM
FROM RAW.ROOFPRINTS;

-- create spatial indexes

CREATE INDEX IF NOT EXISTS ROOFPRINTS_GEOM_IDX ON PROC.ROOFPRINTS USING GIST(GEOM);
CREATE INDEX IF NOT EXISTS ROOFPRINTS_CENTROID_IDX ON PROC.ROOFPRINTS USING GIST(GEOM);