DROP TABLE IF EXISTS PROC.FLOODPLAINS CASCADE;

-- create the table

CREATE TABLE PROC.FLOODPLAINS (
	OID SERIAL PRIMARY KEY,
	FLOODZONE VARCHAR,
	RISKSCORE INTEGER,
	FROMDATE DATE,
	TODATE DATE,
	GEOM GEOMETRY(POLYGON, 2876) NOT NULL
);

-- transfer from raw data

INSERT INTO PROC.FLOODPLAINS (FLOODZONE, RISKSCORE, FROMDATE, TODATE, GEOM)
SELECT 
	FLOODZONE,
	CASE
		WHEN FLOODZONE = 'HHZ' THEN 4 -- high hazard zone is most dangerous/likely
		WHEN FLOODZONE like 'A%' AND FLOODWAY = 1 THEN 3 -- conveyance zone is next
		WHEN FLOODZONE like 'A%' AND FLOODWAY <> 1 THEN 2 --100 year
		WHEN FLOODZONE in ('X', 'B') THEN 1 -- 500 year
	END RISKSCORE,
	EFFDATE::date,
	INEFFDATE::date,
	(ST_DUMP(WKB_GEOMETRY)).GEOM
FROM RAW.FLOODPLAINS;

-- create spatial index

CREATE INDEX IF NOT EXISTS FLOODPLAINS_GEOM_IDX ON PROC.FLOODPLAINS USING GIST(GEOM);