DROP TABLE IF EXISTS FLOOD.FLOODPLAINS CASCADE;

-- create the table from a selection on the sandbox

CREATE TABLE FLOOD.FLOODPLAINS AS
SELECT OBJECTID ID,
	FLOODZONE,
	FLOODWAY,
	CASE
		WHEN FLOODZONE like 'A%' AND FLOODWAY <> 1 THEN '100 Year'
		WHEN FLOODZONE like 'A%' AND FLOODWAY = 1 THEN 'Conveyance Zone'
		WHEN FLOODZONE in ('X', 'B') THEN '500 Year'
		WHEN FLOODZONE = 'HHZ' THEN 'High Hazard Zone'
	END FLOODPLAIN,
	DRAINAGE,
	EFFDATE::date,
	INEFFDATE::date,
	WKB_GEOMETRY GEOM
FROM SANDBOX.FLOODPLAINS;

-- create spatial index

CREATE INDEX IF NOT EXISTS FLOODPLAINS_GEOM_IDX ON FLOOD.FLOODPLAINS USING GIST(GEOM);

-- create sequence and make it the primary key

CREATE SEQUENCE IF NOT EXISTS FLOOD.FLOODPLAINS_ID_SEQ OWNED BY FLOOD.FLOODPLAINS.ID;


ALTER TABLE FLOOD.FLOODPLAINS
ALTER COLUMN ID
SET DEFAULT NEXTVAL('FLOOD.FLOODPLAINS_ID_SEQ'::REGCLASS);


ALTER TABLE FLOOD.FLOODPLAINS ADD CONSTRAINT FLOODPLAINS_PK PRIMARY KEY (ID);

-- alter geometry column to not accept null values

ALTER TABLE FLOOD.FLOODPLAINS
ALTER COLUMN GEOM
SET NOT NULL;