DROP TABLE IF EXISTS FLOOD.PARCELS CASCADE;

-- create the table from a selection on the sandbox

CREATE TABLE FLOOD.PARCELS AS
SELECT OBJECTID,
	ACCOUNTNO,
	PARCELNUM,
	COBPIN,
	SITEADDRESS,
	SITESTRNUM,
	SITESTREET,
	SITESTRPFX,
	SITESTRSFX,
	SITEUNIT,
	BUILDINGYEARPRIM,
	BLDGCLSCD,
	WKB_GEOMETRY GEOM
FROM SANDBOX.PARCELS;

-- create spatial index

CREATE INDEX IF NOT EXISTS PARCELS_GEOM_IDX ON FLOOD.PARCELS USING GIST(GEOM);

-- create sequence and make it the primary key

CREATE SEQUENCE IF NOT EXISTS FLOOD.PARCELS_ID_SEQ OWNED BY FLOOD.PARCELS.OBJECTID;


ALTER TABLE FLOOD.PARCELS
ALTER COLUMN OBJECTID
SET DEFAULT NEXTVAL('FLOOD.PARCELS_ID_SEQ'::REGCLASS);


ALTER TABLE FLOOD.PARCELS ADD CONSTRAINT PARCELS_PK PRIMARY KEY (OBJECTID);

-- alter geometry column to not accept null values

ALTER TABLE FLOOD.PARCELS
ALTER COLUMN GEOM
SET NOT NULL;