DROP TABLE IF EXISTS FLOOD.PARCELS CASCADE;

-- create the table from a selection on the sandbox

CREATE TABLE FLOOD.PARCELS AS
SELECT OBJECTID ID,
	ACCOUNTNO ACCOUNTNUM,
	PARCELNUM,
	COBPIN,
	INITCAP(SITEADDRESS) STRADDRESS,
	SITESTRNUM STRNUM,
	INITCAP(SITESTREET) STREET,
	INITCAP(SITESTRPFX) STRPFIX,
	INITCAP(SITESTRSFX) STRSFIX,
	SITEUNIT UNITNUM,
	BUILDINGYEARPRIM BUILDYEAR,
	WKB_GEOMETRY GEOM
FROM SANDBOX.PARCELS;

-- create spatial index

CREATE INDEX IF NOT EXISTS PARCELS_GEOM_IDX ON FLOOD.PARCELS USING GIST(GEOM);

-- create sequence and make it the primary key

CREATE SEQUENCE IF NOT EXISTS FLOOD.PARCELS_ID_SEQ OWNED BY FLOOD.PARCELS.ID;


ALTER TABLE FLOOD.PARCELS
ALTER COLUMN ID
SET DEFAULT NEXTVAL('FLOOD.PARCELS_ID_SEQ'::REGCLASS);


ALTER TABLE FLOOD.PARCELS ADD CONSTRAINT PARCELS_PK PRIMARY KEY (ID);

-- alter geometry column to not accept null values

ALTER TABLE FLOOD.PARCELS
ALTER COLUMN GEOM
SET NOT NULL;