/* Process and clean all data in the RAW schema to the PROC schema */

-- DROP TABLES

DROP TABLE IF EXISTS PROC.ROOFPRINTS CASCADE;

DROP TABLE IF EXISTS PROC.FLOODPLAINS CASCADE;

DROP TABLE IF EXISTS PROC.PARCELS CASCADE;

-- CREATE TABLES

CREATE TABLE PROC.ROOFPRINTS (
	OID SERIAL PRIMARY KEY,
	BLDGTYPE VARCHAR,
	BLDGYEAR INTEGER,
	GEOM GEOMETRY(POLYGON, 2876) NOT NULL
);

CREATE TABLE PROC.FLOODPLAINS (
	OID SERIAL PRIMARY KEY,
	FLOODZONE VARCHAR,
	FLOODWAY INTEGER,
	FROMDATE DATE,
	TODATE DATE,
	GEOM GEOMETRY(POLYGON, 2876) NOT NULL
);

CREATE TABLE PROC.PARCELS (
	OID SERIAL PRIMARY KEY,
	STRADDRESS VARCHAR,
	BLDGYEAR INTEGER,
	GEOM GEOMETRY(POLYGON, 2876) NOT NULL
);

-- INSERT VALUES FROM RAW

INSERT INTO PROC.ROOFPRINTS (BLDGTYPE, BLDGYEAR, GEOM)
SELECT BLDGTYPE,
	BUILDYEAR,
	(ST_DUMP(WKB_GEOMETRY)).GEOM
FROM RAW.ROOFPRINTS;

INSERT INTO PROC.FLOODPLAINS (FLOODZONE, FLOODWAY, FROMDATE, TODATE, GEOM)
SELECT 
	FLOODZONE,
	FLOODWAY,
	EFFDATE::date,
	INEFFDATE::date,
	(ST_DUMP(WKB_GEOMETRY)).GEOM
FROM RAW.FLOODPLAINS;

INSERT INTO PROC.PARCELS (STRADDRESS, BLDGYEAR, GEOM)
SELECT INITCAP(SITEADDRESS) STRADDRESS,
	BUILDINGYEARPRIM BUILDYEAR,
	(ST_DUMP(WKB_GEOMETRY)).GEOM
FROM RAW.PARCELS;

-- CREATE INDICES

CREATE INDEX ROOFPRINTS_GEOM_IDX ON PROC.ROOFPRINTS USING GIST(GEOM);

CREATE INDEX FLOODPLAINS_GEOM_IDX ON PROC.FLOODPLAINS USING GIST(GEOM);

CREATE INDEX PARCELS_GEOM_IDX ON PROC.PARCELS USING GIST(GEOM);