DROP TABLE IF EXISTS FLOOD.DISSOLVEDBUILDINGS CASCADE;


CREATE TABLE FLOOD.DISSOLVEDBUILDINGS AS 
-- with help from https://gis.stackexchange.com/a/4508/114009
SELECT 0 MULTIROOF,
	SINGLE.BLDGTYPE,
	SINGLE.BUILDYEAR,
	SINGLE.GEOM
FROM FLOOD.BUILDINGS SINGLE
LEFT JOIN FLOOD.TOUCHINGBUILDINGS TOUCH ON ST_INTERSECTS(SINGLE.GEOM, TOUCH.GEOM)
WHERE TOUCH.GEOM IS NULL
UNION ALL
SELECT *
FROM FLOOD.TOUCHINGBUILDINGS;


CREATE INDEX IF NOT EXISTS DISSOLVED_BUILDINGS_GEOM_IDX ON FLOOD.DISSOLVEDBUILDINGS USING GIST(GEOM);